spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    locations: classpath:db/structure, classpath:db/data
    baselineOnMigrate: true
    ignore-missing-migrations: true
    out-of-order: true

jwt:
  secret: sfgsr35663rtjnbksg8gsv233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
  expiration: 3600000 # 1 hour in ms
